export const CONTACTS = [
  {
    id: "1",
    name: "Geneval",
    sobrenome: "Anastacio",
    email: "genevalanastacio@example.com",
    birthDay: "13/07/1968",
    gender: "Masculino",
    language: "Macedonian",
    photo: "https://randomuser.me/api/portraits/men/79.jpg",
  },
  {
    id: "2",
    name: "Rosimere",
    sobrenome: "Nazare",
    email: "rosimerenazare@example.com",
    birthDay: "21/09/1937",
    gender: "Feminino",
    language: "Malagasy",
    photo: "https://randomuser.me/api/portraits/women/25.jpg",
  },
  {
    id: "3",
    name: "Helen",
    sobrenome: "Gonçalves",
    email: "helengoncalves@example.com",
    birthDay: "12/01/2010",
    gender: "Feminino",
    language: "Haitian",
    photo: "https://randomuser.me/api/portraits/women/88.jpg",
  },
  {
    id: "4",
    name: "Débora",
    sobrenome: "Zava",
    email: "deborazava@example.com",
    birthDay: "29/08/1983",
    gender: "Feminino",
    language: "Zhuang",
    photo: "https://randomuser.me/api/portraits/women/62.jpg",
  },
  {
    id: "5",
    name: "Antonietta",
    sobrenome: "Arlia",
    email: "antoniettaarlia@example.com",
    birthDay: "12/06/1982",
    gender: "Feminino",
    language: "Wolof",
    photo: "https://randomuser.me/api/portraits/women/23.jpg",
  },
  {
    id: "6",
    name: "Evelyn",
    sobrenome: "Salomão",
    email: "evelynsalamao@example.com",
    birthDay: "11/08/1949",
    gender: "Feminino",
    language: "Lingala",
    photo: "https://randomuser.me/api/portraits/women/52.jpg",
  },
  {
    id: "7",
    name: "Joemia",
    sobrenome: "Rocha",
    email: "joemiarocha@example.com",
    birthDay: "24/06/1948",
    gender: "Feminino",
    language: "Abkhazian",
    photo: "https://randomuser.me/api/portraits/women/8.jpg",
  },
  {
    id: "8",
    name: "Rodrigo",
    sobrenome: "Prata",
    email: "rodrigoprata@example.com",
    birthDay: "11/05/1943",
    gender: "Masculino",
    language: "Basque",
    photo: "https://randomuser.me/api/portraits/men/28.jpg",
  },
  {
    id: "9",
    name: "Emanoel",
    sobrenome: "Louzano",
    email: "emanoellouzano@example.com",
    birthDay: "18/10/2020",
    gender: "Masculino",
    language: "Interlingua",
    photo: "https://randomuser.me/api/portraits/men/68.jpg",
  },
  {
    id: "10",
    name: "Waleska",
    sobrenome: "Frotté",
    email: "waleskafrotte@example.com",
    birthDay: "25/10/2006",
    gender: "Feminino",
    language: "Tok Pisin",
    photo: "https://randomuser.me/api/portraits/women/73.jpg",
  },
  {
    id: "11",
    name: "Georgiane",
    sobrenome: "Giron",
    email: "georgianegiron@example.com",
    birthDay: "23/10/2023",
    gender: "Feminino",
    language: "Zulu",
    photo: "https://randomuser.me/api/portraits/women/90.jpg",
  },
  {
    id: "12",
    name: "Aline",
    sobrenome: "Dores",
    email: "alinedores@example.com",
    birthDay: "25/11/1991",
    gender: "Feminino",
    language: "Chuvash",
    photo: "https://randomuser.me/api/portraits/women/9.jpg",
  },
  {
    id: "13",
    name: "Erica",
    sobrenome: "Lessa",
    email: "ericalessa@example.com",
    birthDay: "18/08/2005",
    gender: "Feminino",
    language: "Nepali",
    photo: "https://randomuser.me/api/portraits/women/17.jpg",
  },
  {
    id: "14",
    name: "Celia",
    sobrenome: "Soriano",
    email: "celiasoriano@example.com",
    birthDay: "11/12/2002",
    gender: "Feminino",
    language: "Akan",
    photo: "https://randomuser.me/api/portraits/women/20.jpg",
  },
  {
    id: "15",
    name: "Eva",
    sobrenome: "Camara",
    email: "evacamara@example.com",
    birthDay: "01/06/1955",
    gender: "Feminino",
    language: "Inuktitut",
    photo: "https://randomuser.me/api/portraits/women/58.jpg",
  },
  {
    id: "16",
    name: "Adso",
    sobrenome: "Coimbra",
    email: "adsocoimbra@example.com",
    birthDay: "22/02/1968",
    gender: "Masculino",
    language: "English",
    photo: "https://randomuser.me/api/portraits/men/46.jpg",
  },
  {
    id: "17",
    name: "Zilanda",
    sobrenome: "Barsosa",
    email: "zilandabarsosa@example.com",
    birthDay: "15/01/1992",
    gender: "Feminino",
    language: "Sanskrit",
    photo: "https://randomuser.me/api/portraits/women/35.jpg",
  },
  {
    id: "18",
    name: "Otavio",
    sobrenome: "Barcelos",
    email: "otaviobarcelos@example.com",
    birthDay: "11/04/1983",
    gender: "Masculino",
    language: "Inupiaq",
    photo: "https://randomuser.me/api/portraits/men/91.jpg",
  },
  {
    id: "19",
    name: "Lorenna",
    sobrenome: "Carmo",
    email: "lorennacarmo@example.com",
    birthDay: "22/02/1969",
    gender: "Feminino",
    language: "Avestan",
    photo: "https://randomuser.me/api/portraits/women/69.jpg",
  },
  {
    id: "20",
    name: "Jouceli",
    sobrenome: "Maia",
    email: "joucelimaia@example.com",
    birthDay: "15/05/1998",
    gender: "Feminino",
    language: "Tatar",
    photo: "https://randomuser.me/api/portraits/women/53.jpg",
  },
  {
    id: "21",
    name: "Elizabetti",
    sobrenome: "Milanez",
    email: "elizabettimilanez@example.com",
    birthDay: "20/08/2021",
    gender: "Feminino",
    language: "Afrikaans",
    photo: "https://randomuser.me/api/portraits/women/15.jpg",
  },
  {
    id: "22",
    name: "Dayana",
    sobrenome: "Serra",
    email: "dayanaserra@example.com",
    birthDay: "07/02/2015",
    gender: "Feminino",
    language: "Turkmen",
    photo: "https://randomuser.me/api/portraits/women/92.jpg",
  },
  {
    id: "23",
    name: "Juliana",
    sobrenome: "Pires",
    email: "julianapires@example.com",
    birthDay: "22/11/1985",
    gender: "Feminino",
    language: "Esperanto",
    photo: "https://randomuser.me/api/portraits/women/16.jpg",
  },
  {
    id: "24",
    name: "Ruan",
    sobrenome: "Cruz",
    email: "ruancruz@example.com",
    birthDay: "29/11/1944",
    gender: "Masculino",
    language: "Kikuyu",
    photo: "https://randomuser.me/api/portraits/men/32.jpg",
  },
  {
    id: "25",
    name: "Valmir",
    sobrenome: "Monteiro",
    email: "valmirmonteiro@example.com",
    birthDay: "04/08/1954",
    gender: "Masculino",
    language: "Ukrainian",
    photo: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: "26",
    name: "Fábio",
    sobrenome: "Hall",
    email: "fabiohall@example.com",
    birthDay: "15/05/1999",
    gender: "Masculino",
    language: "Swati",
    photo: "https://randomuser.me/api/portraits/men/59.jpg",
  },
  {
    id: "27",
    name: "Dalva",
    sobrenome: "Borges",
    email: "dalvaborges@example.com",
    birthDay: "08/09/2015",
    gender: "Feminino",
    language: "Kinyarwanda",
    photo: "https://randomuser.me/api/portraits/women/56.jpg",
  },
  {
    id: "28",
    name: "Telmo",
    sobrenome: "Corrêa",
    email: "telmocorrea@example.com",
    birthDay: "03/12/1972",
    gender: "Masculino",
    language: "Hausa",
    photo: "https://randomuser.me/api/portraits/men/73.jpg",
  },
  {
    id: "29",
    name: "Franciele",
    sobrenome: "Giacomini",
    email: "francielegiacomini@example.com",
    birthDay: "30/07/1936",
    gender: "Feminino",
    language: "Dzongkha",
    photo: "https://randomuser.me/api/portraits/women/44.jpg",
  },
  {
    id: "30",
    name: "Silvia",
    sobrenome: "Borges",
    email: "silviaborges@example.com",
    birthDay: "26/09/1976",
    gender: "Feminino",
    language: "Sango",
    photo: "https://randomuser.me/api/portraits/women/76.jpg",
  },
  {
    id: "31",
    name: "Odileia",
    sobrenome: "Peres",
    email: "odileiaperes@example.com",
    birthDay: "08/03/1954",
    gender: "Feminino",
    language: "Latvian",
    photo: "https://randomuser.me/api/portraits/women/55.jpg",
  },
  {
    id: "32",
    name: "Maria Adelia",
    sobrenome: "Paes",
    email: "mariaadeliaperes@example.com",
    birthDay: "06/02/1991",
    gender: "Feminino",
    language: "Ido",
    photo: "https://randomuser.me/api/portraits/women/66.jpg",
  },
  {
    id: "33",
    name: "Adolfo",
    sobrenome: "Nobrega",
    email: "adolfonobrega@example.com",
    birthDay: "14/08/1936",
    gender: "Masculino",
    language: "Korean",
    photo: "https://randomuser.me/api/portraits/men/61.jpg",
  },
  {
    id: "34",
    name: "Elio",
    sobrenome: "Barros",
    email: "eliobarros@example.com",
    birthDay: "28/04/1979",
    gender: "Masculino",
    language: "Croatian",
    photo: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    id: "35",
    name: "Dayvid",
    sobrenome: "Facre",
    email: "dayvidfacre@example.com",
    birthDay: "09/03/2016",
    gender: "Masculino",
    language: "Navajo",
    photo: "https://randomuser.me/api/portraits/men/70.jpg",
  },
  {
    id: "36",
    name: "Isaque",
    sobrenome: "Torres",
    email: "isaquetorres@example.com",
    birthDay: "05/06/1957",
    gender: "Masculino",
    language: "Polish",
    photo: "https://randomuser.me/api/portraits/men/9.jpg",
  },
  {
    id: "37",
    name: "Adriano",
    sobrenome: "Marica",
    email: "adrianomarica@example.com",
    birthDay: "13/10/1965",
    gender: "Masculino",
    language: "Bulgarian",
    photo: "https://randomuser.me/api/portraits/men/65.jpg",
  },
  {
    id: "38",
    name: "Humberto",
    sobrenome: "Carmoriz",
    email: "humbertocarmoriz@example.com",
    birthDay: "25/04/1967",
    gender: "Masculino",
    language: "Kanuri",
    photo: "https://randomuser.me/api/portraits/men/57.jpg",
  },
  {
    id: "39",
    name: "Marcele",
    sobrenome: "Campos",
    email: "marcelecampos@example.com",
    birthDay: "14/09/1990",
    gender: "Feminino",
    language: "Breton",
    photo: "https://randomuser.me/api/portraits/women/28.jpg",
  },
  {
    id: "40",
    name: "Ana Beatriz",
    sobrenome: "Ascar",
    email: "anabeatrizascar@example.com",
    birthDay: "06/04/1959",
    gender: "Feminino",
    language: "Bosnian",
    photo: "https://randomuser.me/api/portraits/women/54.jpg",
  },
  {
    id: "41",
    name: "José Mário",
    sobrenome: "Viana",
    email: "josemarioviana@example.com",
    birthDay: "19/08/1942",
    gender: "Masculino",
    language: "Ojibwa",
    photo: "https://randomuser.me/api/portraits/men/37.jpg",
  },
  {
    id: "42",
    name: "Aurélio",
    sobrenome: "Billé",
    email: "aureliobille@example.com",
    birthDay: "30/12/1940",
    gender: "Masculino",
    language: "Lao",
    photo: "https://randomuser.me/api/portraits/men/86.jpg",
  },
  {
    id: "43",
    name: "Rinaldo",
    sobrenome: "Barroso",
    email: "rinaldobarroso@example.com",
    birthDay: "22/05/1938",
    gender: "Masculino",
    language: "Avaric",
    photo: "https://randomuser.me/api/portraits/men/52.jpg",
  },
  {
    id: "44",
    name: "Silvia",
    sobrenome: "Dinis",
    email: "silviadinis@example.com",
    birthDay: "10/07/1944",
    gender: "Feminino",
    language: "Corsican",
    photo: "https://randomuser.me/api/portraits/women/6.jpg",
  },
  {
    id: "45",
    name: "Cris",
    sobrenome: "Hall",
    email: "crishall@example.com",
    birthDay: "26/06/1982",
    gender: "Feminino",
    language: "Kazakh",
    photo: "https://randomuser.me/api/portraits/women/30.jpg",
  },
  {
    id: "46",
    name: "Monique",
    sobrenome: "Araújo",
    email: "moniquearaujo@example.com",
    birthDay: "20/07/1970",
    gender: "Feminino",
    language: "Bihari",
    photo: "https://randomuser.me/api/portraits/women/67.jpg",
  },
  {
    id: "47",
    name: "Mayane",
    sobrenome: "Uchôa",
    email: "mayanauchoa@example.com",
    birthDay: "01/12/1944",
    gender: "Feminino",
    language: "Limburgish",
    photo: "https://randomuser.me/api/portraits/women/50.jpg",
  },
  {
    id: "48",
    name: "Ledir",
    sobrenome: "Costa",
    email: "ledircosta@example.com",
    birthDay: "05/10/1958",
    gender: "Feminino",
    language: "Panjabi",
    photo: "https://randomuser.me/api/portraits/women/83.jpg",
  },
  {
    id: "49",
    name: "Frank",
    sobrenome: "Queiroga",
    email: "frankqueiroga@example.com",
    birthDay: "25/11/2023",
    gender: "Masculino",
    language: "Russian",
    photo: "https://randomuser.me/api/portraits/men/50.jpg",
  },
  {
    id: "50",
    name: "Juan",
    sobrenome: "Rosa",
    email: "juanrosa@example.com",
    birthDay: "23/10/1981",
    gender: "Masculino",
    language: "Malayalam",
    photo: "https://randomuser.me/api/portraits/men/49.jpg",
  },
  {
    id: "51",
    name: "Ignácio Goulart",
    email: "ignaciogoulart@example.com",
    birthDay: "18/08/2007",
    gender: "Masculino",
    language: "Javanese",
    photo: "https://randomuser.me/api/portraits/men/60.jpg",
  },
  {
    id: "52",
    name: "Yago Prata",
    email: "yagoprata@example.com",
    birthDay: "18/05/1977",
    gender: "Masculino",
    language: "Maori",
    photo: "https://randomuser.me/api/portraits/men/88.jpg",
  },
  {
    id: "53",
    name: "Marcy dos Santos",
    email: "marcydossantos@example.com",
    birthDay: "08/07/2006",
    gender: "Feminino",
    language: "Pali",
    photo: "https://randomuser.me/api/portraits/women/71.jpg",
  },
  {
    id: "54",
    name: "Thamirys Jesus",
    email: "thamirysjesus@example.com",
    birthDay: "31/07/1963",
    gender: "Feminino",
    language: "Guarani",
    photo: "https://randomuser.me/api/portraits/women/43.jpg",
  },
];
